### ISSUE TITLE
Extra "/" in README.md

### ISSUE THREAD

**Issue by cpeavy2** [SV-ROS/intro_to_ros#5]
Extra "/" in intro_to_ros README.md ... under "Optional, but highly recommended:"
 
git clone /https://github.com/pirobot/rbx1
 
Thanks,
Camp

**Comment by rcxking** [comment]
Hi Camp, I'll start making some contributions to this repo.  I have a PR to tackle this issue: https://github.com/SV-ROS/intro_to_ros/pull/9

**Comment by cpeavy2** [comment]
Very good! - cp

    On Friday, June 7, 2019, 11:02:37 PM PDT, Bryant <notifications@github.com> wrote:  
 
 
Hi Camp, I'll start making some contributions to this repo. I have a PR to tackle this issue: #9

**Comment by rcxking** [comment]
Merged in PR #9 6/9/19 to address this issue.  Closing.
